### ISSUE TITLE
Accessibility Model? 

### ISSUE THREAD

**Issue by Slusep** [Informatievlaanderen/OSLOthema-mobiliteitDienstregelingEnPlanning#12]
What are the plans for developping an accessibility model? The following items from MMTIS delegated regulation 2017/1926 list the following items that I don't see correctly supported. 

Level 1

(vii) Stop facilities access nodes (including platform information, help desks/information points, ticket booths,
lifts/stairs, entrances and exit locations)
(viii) Vehicles (low floor; wheelchair accessible.)
(ix) Accessibility of access nodes, and paths within an interchange (such as existence of lifts, escalators)
(x) Existence of assistance services (such as existence of on-site assistance
Level 2
b) Information service:
Where and how to buy tickets for scheduled modes, demand responsive modes 
modes and demand-responsive incl. retail channels, fulfilment methods, payment methods)
(ii) Vehicle facilities such as classes of carriage, on-board Wi-Fi.

In term of vehicule facilities we have a nice set of additional facilities that could be included such as
bike allowed
luggage racks and size
quiet vehicle
wifi
toilet
air conditioning
single / double deck

**Comment by skinkie** [comment]
You want to check EPIAP.

**Comment by GeertThijs** [comment]
> EPIAP

Could not find a specification, probably because it still is in development?

**Comment by skinkie** [comment]
> > EPIAP
> 
> Could not find a specification, probably because it still is in development?

It is being voted on, but you can access it via basecamp or check the XSD in the repository.
https://github.com/NeTEx-CEN/NeTEx/tree/EPIAP

**Comment by GeertThijs** [comment]
> In term of vehicule facilities we have a nice set of additional facilities that could be included such as bike allowed luggage racks and size quiet vehicle wifi toilet air conditioning single / double deck

There is a[ ServiceFacilitySet](file:///C:/Users/thijsge/Downloads/index_en%20(36).html#Service%20Facility%20Set) class in the model, but it had no attributes until now. This is corrected in the current version: attributes commonFacility, serviceFacility and accomodation were added, the latter further attributed with fareClass, accomodationFacility, nuisanceFacility and passengerCommsFacility. Corresponding enumerations were added which will have to be developed as skos:Conceptschemes with values from annex B of EPIP.

**Comment by Slusep** [comment]
That's a smart solution :) like that. Shall the Specifications be updated as well

**Comment by GeertThijs** [comment]
Follow the versionless link to navigate to the latest version: https://purl.eu/doc/applicationprofile/netex-belgium/timetables-ap/index_en.html. I still have to write the definitions and usageNotes though.

**Comment by GeertThijs** [comment]
Definitions written. This one can be closed.

**Comment by Slusep** [comment]
agreed for closing
