### ISSUE TITLE
frequency

### ISSUE THREAD

**Issue by Slusep** [Informatievlaanderen/OSLOthema-mobiliteitDienstregelingEnPlanning#13]
In the timetable model 
https://purl.eu/doc/applicationprofile/netex-belgium/timetables-ap/working-draft/2022-04-21
for the following
[Journey Frequency](https://purl.eu/ns/mobility/timetables-and-planning#JourneyFrequency)

Only [Headway Interval](https://purl.eu/doc/applicationprofile/netex-belgium/timetables-ap/#Headway%20Interval) is curretly part of the model 
but to properly use frequency trip based information in route planners or start time and end time should be supported or start time and number of occurences should be supported
because you define 3 options for HeadwayInterval (max min or scheduled)  
[Hadway Interval](https://purl.eu/ns/mobility/timetables-and-planning#HeadwayInterval)
I recommend to support start time and end time or have a clear linkage with the service calendar

**Comment by GeertThijs** [comment]
JourneyFrequency is removed from the model, it was unintentionally added but without using it. Only HeadwayInterval is used as you mention, as an attribute from TimeTabledPassingTime, so with a departure anbd an arrival time.

**Comment by Slusep** [comment]
Clear for me, shall the documentation be updated as well?

**Comment by GeertThijs** [comment]
Follow the versionless link to navigate to the latest version: https://purl.eu/doc/applicationprofile/netex-belgium/timetables-ap/index_en.html.

**Comment by Slusep** [comment]
Thanks Geert, closing
