### ISSUE TITLE
Timetables profile -) Service Journey train size type enumeration

### ISSUE THREAD

**Issue by Slusep** [Informatievlaanderen/OSLOthema-mobiliteitDienstregelingEnPlanning#8]
In the Timetables profile, for the entity ServiceJourney, one of the attribute is trainsize
[train size](https://purl.eu/ns/mobility/timetables-and-planning#trainSize)
we associate an enumeration to it currently normal short or long
Bus operators might want to also support their vehicule size using this field I suggest to increase the enum with at minimum
doublebus
triplebus
minibus
TEC STIB and Delijn please comment :)

**Comment by GeertThijs** [comment]
There is some overlap here between TrainsizeType and VehicleType. I should think that you can have a short doublebus and a short one, combining both aspects I mean. And again: the current codelists in the diagram are for illustrative purposes only, they should be developed as skos:Conceptschemas before or at implementation time.

**Comment by Slusep** [comment]
clear for me, closing
