### ISSUE TITLE
Line Entity - Line color

### ISSUE THREAD

**Issue by Slusep** [Informatievlaanderen/OSLOthema-mobiliteitDienstregelingEnPlanning#9]
I think one of the properties of the Line is "color" and it seems to be missing. Two examples: Brussels metro, the map is represented by colors that are/could be used by users. Line colors are also used to identify lines for Charleroi Metro

**Comment by GeertThijs** [comment]
This was indeed missing, that is to say: the Presentation class was there in the model (along with the Line.presentation attribute), but it had not attributes. One of these is Presentation.color but there are others (like textFont) which I have added now. All this in accordanbce with the EPIP profile of NETEX of course.

**Comment by GeertThijs** [comment]
This one can be closed.
